/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.ijse.sellingsystem.controller.CustomerAddController;
import lk.ijse.sellingsystem.core.dto.CustomerDTO;
import lk.ijse.sellingsystem.idgenerator.IDGenerator;

/**
 *
 * @author Samishka
 */
public class CashePayment extends javax.swing.JPanel {

    /**
     * Creates new form CashePayment
     */
    public CashePayment() {
        initComponents();
        loadData();
        loadDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        txtPaymentId = new org.jdesktop.swingx.JXTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        txtDate = new org.jdesktop.swingx.JXTextField();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        cmbCustomerId = new org.jdesktop.swingx.JXComboBox();

        jXPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPaymentId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPaymentId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPaymentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIdActionPerformed(evt);
            }
        });
        jXPanel3.add(txtPaymentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 30));

        jXLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel8.setText("Payment  ID");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXPanel3.add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 130, 30));

        txtDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jXPanel3.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, 30));

        jXLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel11.setText("Date");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXPanel3.add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 30));

        jXLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel13.setText("Customer ID");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jXPanel3.add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 130, 30));
        jXPanel3.add(cmbCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jXPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jXPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIdActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXComboBox cmbCustomerId;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXTextField txtDate;
    private org.jdesktop.swingx.JXTextField txtPaymentId;
    // End of variables declaration//GEN-END:variables

    private void loadData() {

        try {

            String orderId;
            orderId = IDGenerator.getNewBatch1ID("Payment", "id", "P");
            txtPaymentId.setText(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         try {
            ArrayList<CustomerDTO>allCustomer=CustomerAddController.getAllCustomers();
            
            cmbCustomerId.removeAllItems();
            if(allCustomer==null) return;
            
            for (CustomerDTO allVehicle : allCustomer) {
                cmbCustomerId.addItem(allVehicle.getId());
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadDate() {
        Date d1 = new Date(); //request current data
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String fDate = df.format(d1);
        txtDate.setText(fDate);

    }

}
