/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;
import java.awt.Dialog;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import lk.ijse.sellingsystem.controller.CustomerAddController;
import lk.ijse.sellingsystem.controller.CustomerPaymentController;
import lk.ijse.sellingsystem.controller.PaymentController;
import lk.ijse.sellingsystem.core.dto.CustomerDTO;
import lk.ijse.sellingsystem.core.dto.PaymentDTO;
import lk.ijse.sellingsystem.core.dto.PaymentTypeDTO;
import lk.ijse.sellingsystem.idgenerator.IDGenerator;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Samishka
 */
@Report("lk.ijse.sellingsystem.report")
public class CustomerPayment extends javax.swing.JPanel {

    /**
     * Creates new form Payment
     */
    public CustomerPayment() {
        initComponents();
        loadPayment();
        //loadData();
        loadDate();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentView = new org.jdesktop.swingx.JXTable();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        btnPrint = new org.jdesktop.swingx.JXLabel();
        btnNew = new org.jdesktop.swingx.JXLabel();
        btnDelete = new org.jdesktop.swingx.JXLabel();
        btnSave = new org.jdesktop.swingx.JXLabel();
        txtDate = new org.jdesktop.swingx.JXTextField();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        txtPaymentId = new org.jdesktop.swingx.JXTextField();
        cmbPaymentType = new org.jdesktop.swingx.JXComboBox();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        txtPaymentTypeId = new org.jdesktop.swingx.JXTextField();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jXLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jXLabel2.setText("PAYMENT ");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel2);

        jXLabel1.setBackground(new java.awt.Color(235, 235, 235));
        jXPanel1.add(jXLabel1);

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        tblPaymentView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Payment type ID", "Payment Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPaymentView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaymentViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaymentView);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 590, 510));

        jXPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setBackground(new java.awt.Color(153, 153, 153));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/print1.png"))); // NOI18N
        btnPrint.setText("REPORT");
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrint.setOpaque(true);
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });
        jXPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 40));

        btnNew.setBackground(new java.awt.Color(153, 153, 153));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        jXPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        jXPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 40));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        jXPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 90, 40));

        add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        txtDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, 30));

        jXLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel11.setText("Date");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 30));

        txtPaymentId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPaymentId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPaymentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIdActionPerformed(evt);
            }
        });
        add(txtPaymentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));
        add(cmbPaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 150, 30));

        jXLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel13.setText("Payment Type");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 100, 30));

        jXLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel8.setText("Payment  ID");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 30));

        txtPaymentTypeId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPaymentTypeId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPaymentTypeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentTypeIdActionPerformed(evt);
            }
        });
        add(txtPaymentTypeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 30));

        jXLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel12.setText("Payment type ID");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPaymentViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaymentViewMouseClicked
       
    }//GEN-LAST:event_tblPaymentViewMouseClicked

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/print2.png"));
        btnPrint.setIcon(icon);
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        btnPrint.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/print1.png"));
        btnPrint.setIcon(icon);
    }//GEN-LAST:event_btnPrintMouseExited

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
       

    }//GEN-LAST:event_btnNewMouseClicked

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add 4_1.png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete5.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        
        try {
            PaymentDTO paymentDTO;
            paymentDTO = new PaymentDTO(
                    txtPaymentId.getText(),
                    txtDate.getText(),
                    txtPaymentTypeId.getText()
            );
            
            PaymentTypeDTO paymentTypeDTO=new PaymentTypeDTO(txtPaymentTypeId.getText(), cmbPaymentType.getSelectedItem().toString());

            boolean result = PaymentController.addPayment(paymentDTO,paymentTypeDTO);

            if (result) {
                JOptionPane.showMessageDialog(this, "Payment has been successfully added.");
                loadPayment();
            } else {
                JOptionPane.showMessageDialog(this, "Payment hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav3.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseExited

    private void txtPaymentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIdActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try {
            PaymentDTO payment=new PaymentDTO(
                    txtPaymentId.getText(),
                    txtDate.getText(),
                    txtPaymentTypeId.getText(),
                    cmbPaymentType.getSelectedItem().toString()
            );
            boolean result = CustomerPaymentController.deletePayment(payment);
            if (result) {

            }
 
        } catch (Exception ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadPayment();

    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtPaymentTypeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentTypeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentTypeIdActionPerformed

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
         JasperUtil.init(CustomerPayment.class);

        JasperReportsContext ctx = JasperUtil.getReportContext();

        try {
            JasperReport compiledReport = JasperUtil.getCompiledReport("Payment.jasper");
            
            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
            
            HashMap<String, Object> reportParams = new HashMap<>();
            
            TableModel model = tblPaymentView.getModel();
            
            JasperPrint filledReport = fillManager.
                    fill(compiledReport, reportParams, new JRTableModelDataSource(model));
            
            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
            frmJasperViewer.setTitle("Order List");
            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewer.setVisible(true);
            
            
        } catch (JRException ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPrintMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel btnDelete;
    private org.jdesktop.swingx.JXLabel btnNew;
    private org.jdesktop.swingx.JXLabel btnPrint;
    private org.jdesktop.swingx.JXLabel btnSave;
    private org.jdesktop.swingx.JXComboBox cmbPaymentType;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTable tblPaymentView;
    private org.jdesktop.swingx.JXTextField txtDate;
    private org.jdesktop.swingx.JXTextField txtPaymentId;
    private org.jdesktop.swingx.JXTextField txtPaymentTypeId;
    // End of variables declaration//GEN-END:variables

    private void loadPayment() {
         
            try {
                ArrayList<PaymentDTO> payment = CustomerPaymentController.getAllCustomers();
                
                DefaultTableModel dtm = (DefaultTableModel) tblPaymentView.getModel();
                
                dtm.setRowCount(0);
                
                if (payment != null) {
                    
                    for (PaymentDTO customer : payment) {
                        
                        Object[] rowData = {
                            customer.getId(),
                            
                            customer.getDate(),
                            customer.getPaymentId(),
                              cmbPaymentType.getSelectedItem(),
                        
                        };
                        
                        dtm.addRow(rowData);
                        
                    }
                    
                }
            } catch (Exception ex) {
                Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
      private void loadData() {

        try {

            String orderId;
            orderId = IDGenerator.getNewBatch1ID("Payment", "id", "P");
            txtPaymentId.setText(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         try {

            String orderId;
            orderId = IDGenerator.getNewBatch1ID("Payment", "id", "PT");
            txtPaymentTypeId.setText(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
       
          
       
        
        
        
        
        
        
        
        
        
        
        
        

         
         
         cmbPaymentType.addItem("Cache");
         cmbPaymentType.addItem("Lease");

    }

    private void loadDate() {
        Date d1 = new Date(); //request current data
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String fDate = df.format(d1);
        txtDate.setText(fDate);

    }

}
    

