/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;
import java.awt.Dialog;
import java.math.BigDecimal;
import java.sql.Array;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import lk.ijse.sellingsystem.controller.CustomerAddController;
import lk.ijse.sellingsystem.controller.VehicleController;
import lk.ijse.sellingsystem.core.dto.CustomerDTO;
import lk.ijse.sellingsystem.core.dto.VehicleDTO;
import lk.ijse.sellingsystem.idgenerator.IDGenerator;
import static lk.ijse.sellingsystem.view.Home.MainPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Lahiru Samishka
 */
@Report("lk.ijse.sellingsystem.report")
public class CustomerAdd extends javax.swing.JPanel {

    /**
     * Creates new form pnlCustomer
     */
    public CustomerAdd() {
        initComponents();
        setDate();
        OrderID();
        loadAllCustomers();
        loadDetails();

    }

    private void loadAllCustomers() {

        try {
            
            try {
                ArrayList<CustomerDTO> allCustomers = CustomerAddController.getAllCustomers();
                
                DefaultTableModel dtm = (DefaultTableModel) tblCustomerView.getModel();
                
                dtm.setRowCount(0);
                
                if (allCustomers != null) {
                    
                    for (CustomerDTO customer : allCustomers) {
                        
                        Object[] rowData = {
                            customer.getId(),
                            customer.getName(),
                            customer.getAddress(),
                            customer.getAdvance()
                            
                            
                            
                            ,};
                        
                        dtm.addRow(rowData);
                        
                    }
                    
                }
            } catch (Exception ex) {
                Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            ArrayList<VehicleDTO>allVehicles=VehicleController.getAllVehicles();
            
            cmbVehicleId.removeAllItems();
            if(allVehicles==null) return;
            
            for (VehicleDTO allVehicle : allVehicles) {
                cmbVehicleId.addItem(allVehicle.getId());
            }
           
            
        } catch (Exception ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new org.jdesktop.swingx.JXTextField();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        txtCustomeName = new org.jdesktop.swingx.JXTextField();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtCustomerAddress = new org.jdesktop.swingx.JXTextField();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtPhoneno = new org.jdesktop.swingx.JXTextField();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        txtCustomerID = new org.jdesktop.swingx.JXTextField();
        txtGender = new org.jdesktop.swingx.JXTextField();
        txtCustomerNIC = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerView = new org.jdesktop.swingx.JXTable();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        txtAdvancePayment = new org.jdesktop.swingx.JXTextField();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        txtDate = new org.jdesktop.swingx.JXTextField();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        btnNew = new org.jdesktop.swingx.JXLabel();
        btnDelete = new org.jdesktop.swingx.JXLabel();
        btnSave = new org.jdesktop.swingx.JXLabel();
        btnInvoice = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        cmbVehicleId = new org.jdesktop.swingx.JXComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 380, 30));

        jXLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel4.setText("Gender");
        jXLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 30));

        jXLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel5.setText("Customer  Name");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 30));

        txtCustomeName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomeName.setForeground(new java.awt.Color(102, 102, 102));
        txtCustomeName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomeNameActionPerformed(evt);
            }
        });
        add(txtCustomeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 380, 30));

        jXLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel6.setText("Customer  Address");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, 30));

        txtCustomerAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomerAddress.setForeground(new java.awt.Color(102, 102, 102));
        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAddressActionPerformed(evt);
            }
        });
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 380, 30));

        jXLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel7.setText("Phone Number");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 30));

        txtPhoneno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPhoneno.setForeground(new java.awt.Color(102, 102, 102));
        txtPhoneno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPhoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhonenoActionPerformed(evt);
            }
        });
        add(txtPhoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 30));

        jXLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel8.setText("Customer  NIC");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jXLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel9.setText("Email Address");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 30));

        txtCustomerID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomerID.setForeground(new java.awt.Color(102, 102, 102));
        txtCustomerID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerID.setNextFocusableComponent(txtCustomerNIC);
        txtCustomerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIDActionPerformed(evt);
            }
        });
        add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 30));

        txtGender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtGender.setForeground(new java.awt.Color(102, 102, 102));
        txtGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 120, 30));

        txtCustomerNIC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomerNIC.setForeground(new java.awt.Color(102, 102, 102));
        txtCustomerNIC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerNIC.setNextFocusableComponent(txtCustomeName);
        txtCustomerNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNICActionPerformed(evt);
            }
        });
        txtCustomerNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerNICKeyReleased(evt);
            }
        });
        add(txtCustomerNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, 30));

        tblCustomerView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Advance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCustomerView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomerView);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 37, 520, 510));

        jXLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel16.setText("Customer ID");
        jXLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 30));

        jXLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel11.setText("Vehicle ID");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 120, 30));

        txtAdvancePayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAdvancePayment.setForeground(new java.awt.Color(102, 102, 102));
        txtAdvancePayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAdvancePayment.setNextFocusableComponent(txtCustomerNIC);
        txtAdvancePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvancePaymentActionPerformed(evt);
            }
        });
        add(txtAdvancePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 120, 30));

        jXLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel12.setText("Advance Payment");
        jXLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, 30));

        jXLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel13.setText("Date");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 30, 30));

        txtDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDate.setForeground(new java.awt.Color(102, 102, 102));
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 90, 30));

        jXPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setBackground(new java.awt.Color(153, 153, 153));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        jXPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        jXPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 40));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        jXPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 40));

        btnInvoice.setBackground(new java.awt.Color(153, 153, 153));
        btnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/print1.png"))); // NOI18N
        btnInvoice.setText(" PRINT");
        btnInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInvoice.setOpaque(true);
        btnInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseExited(evt);
            }
        });
        jXPanel2.add(btnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 130, 40));

        add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 410, 40));

        jXPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jXLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jXLabel2.setText("ADD CUSTOMER ");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel2);

        jXLabel1.setBackground(new java.awt.Color(235, 235, 235));
        jXPanel1.add(jXLabel1);

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));
        add(cmbVehicleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCustomeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomeNameActionPerformed

    private void txtPhonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhonenoActionPerformed

    private void txtCustomerNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNICActionPerformed

    private void txtCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAddressActionPerformed

    private void txtCustomerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIDActionPerformed
        // dfdf
    }//GEN-LAST:event_txtCustomerIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed


    private void tblCustomerViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerViewMouseClicked
        try {
            String itemId = (String) tblCustomerView.getValueAt(tblCustomerView.getSelectedRow(), 0);
            CustomerDTO customerDTO = new CustomerDTO();
            customerDTO.setId(itemId);
            CustomerDTO searchCustomer = CustomerAddController.searchCustomer(customerDTO);
            txtCustomerID.setText(searchCustomer.getId());
            txtCustomerNIC.setText(searchCustomer.getNic());
            txtCustomeName.setText(searchCustomer.getName());
            txtCustomerAddress.setText(searchCustomer.getAddress());
            txtEmail.setText(searchCustomer.getEmail());
            txtPhoneno.setText(searchCustomer.getPhoneNo());
            cmbVehicleId.setSelectedItem(searchCustomer.getVehicleId());
            txtAdvancePayment.setText(searchCustomer.getAdvance().toString());
            txtDate.setText(searchCustomer.getDate());

        } catch (Exception ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_tblCustomerViewMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        String supplierName = txtCustomeName.getText();

        if (!supplierName.matches("[A-Za-z. ]+")) {
            JOptionPane.showMessageDialog(this, "Please enter valid supplier name");
            txtCustomeName.selectAll();
            txtCustomeName.requestFocusInWindow();
            return;
        }
        String supplierNIC = txtCustomerNIC.getText();

        if (!supplierNIC.matches("\\d{9}[Vv]")) {
            JOptionPane.showMessageDialog(this, "Please enter valid supplier nic");
            txtCustomerNIC.selectAll();
            txtCustomerNIC.requestFocusInWindow();
            return;
        }

        String supplierContactNumber = txtPhoneno.getText();

        if (!supplierContactNumber.matches("\\d{3}\\d{7}")) {
            JOptionPane.showMessageDialog(this, "Please enter valid supplier contact number");
            txtPhoneno.selectAll();
            txtPhoneno.requestFocusInWindow();
            return;
        }
        //save button
        try {
            CustomerDTO customer;
            customer = new CustomerDTO(
                    txtCustomerID.getText(),
                    txtCustomerNIC.getText(),
                    txtCustomeName.getText(),
                    txtCustomerAddress.getText(),
                    txtPhoneno.getText(),
                    cmbVehicleId.getSelectedItem().toString(),
                    new BigDecimal(txtAdvancePayment.getText()),
                    txtDate.getText(),
                    txtEmail.getText()
            );

            boolean result = CustomerAddController.addCustomer(customer);

            if (result) {
                JOption mass = new JOption();
                mass.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Customer hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllCustomers();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav3.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        clearAllTextFileds();
        // txtCustomerNIC.requestFocus();

        CustomerAdd order = new CustomerAdd();
        Home.MainPanel.removeAll();
        order.setSize(Home.MainPanel.getSize());
        Home.MainPanel.add(order);
        Home.MainPanel.revalidate();
        Home.MainPanel.repaint();
        txtCustomerNIC.requestFocus();
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete5.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add 4_1.png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseExited

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try {
            CustomerDTO customer = new CustomerDTO(
                    txtCustomerID.getText(),
                    txtCustomerNIC.getText(),
                    txtCustomeName.getText(),
                    txtCustomerAddress.getText(),
                    txtPhoneno.getText(),
                    cmbVehicleId.getSelectedItem().toString(),
                    new BigDecimal(txtAdvancePayment.getText()),
                    txtDate.getText(),
                    txtEmail.getText()
            );
            boolean result = CustomerAddController.deleteCustomer(customer);
            if (result) {

            }

        } catch (Exception ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
         loadAllCustomers();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAdvancePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvancePaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdvancePaymentActionPerformed

    private void txtCustomerNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNICKeyReleased
        String nic = txtCustomerNIC.getText();
        String M = "Male", F = "Female";
        int d = Integer.parseInt(nic.substring(2, 5));
        if (d > 500) {
            txtGender.setText("Female");
        } else {
            txtGender.setText("Male");
        }

    }//GEN-LAST:event_txtCustomerNICKeyReleased

    private void btnInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseClicked

        JasperUtil.init(CustomerAdd.class);

        JasperReportsContext ctx = JasperUtil.getReportContext();

        try {
            JasperReport compiledReport = JasperUtil.getCompiledReport("VehicleDetails.jasper");

            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);

            HashMap<String, Object> reportParams = new HashMap<>();

            TableModel model = tblCustomerView.getModel();

            JasperPrint filledReport = fillManager.
            fill(compiledReport, reportParams, new JRTableModelDataSource(model));

            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
            frmJasperViewer.setTitle("Customer List");
            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInvoiceMouseClicked

    private void btnInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseEntered

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/print2.png"));
        btnInvoice.setIcon(icon);
    }//GEN-LAST:event_btnInvoiceMouseEntered

    private void btnInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseExited
        btnInvoice.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/print1.png"));
        btnInvoice.setIcon(icon);
    }//GEN-LAST:event_btnInvoiceMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel btnDelete;
    private org.jdesktop.swingx.JXLabel btnInvoice;
    private org.jdesktop.swingx.JXLabel btnNew;
    private org.jdesktop.swingx.JXLabel btnSave;
    private org.jdesktop.swingx.JXComboBox cmbVehicleId;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTable tblCustomerView;
    private org.jdesktop.swingx.JXTextField txtAdvancePayment;
    private org.jdesktop.swingx.JXTextField txtCustomeName;
    private org.jdesktop.swingx.JXTextField txtCustomerAddress;
    private org.jdesktop.swingx.JXTextField txtCustomerID;
    private org.jdesktop.swingx.JXTextField txtCustomerNIC;
    private org.jdesktop.swingx.JXTextField txtDate;
    private org.jdesktop.swingx.JXTextField txtEmail;
    private org.jdesktop.swingx.JXTextField txtGender;
    private org.jdesktop.swingx.JXTextField txtPhoneno;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d1 = new Date(); //request current data
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String fDate = df.format(d1);
        txtDate.setText(fDate);
    }

    private void clearAllTextFileds() {
        txtCustomerNIC.setText("");
        txtCustomeName.setText("");
        txtCustomerAddress.setText("");
        txtEmail.setText("");
        txtPhoneno.setText("");
        txtGender.setText("");

        txtAdvancePayment.setText("");

    }

    private void OrderID() {

        try {
            String orderId;
            orderId = IDGenerator.getNewID("Customer", "id", "C");
            txtCustomerID.setText(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadDetails() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblCustomerView.getModel();
            model.setRowCount(0);
            ArrayList<CustomerDTO> allCustomers = CustomerAddController.getAllCustomers();

            for (CustomerDTO allCustomer : allCustomers) {
                Object[] rowData = {
                    allCustomer.getId(),
                    allCustomer.getAddress(),
                    allCustomer.getName()
                   
                };
                model.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
