/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;
import java.awt.Dialog;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import lk.ijse.sellingsystem.controller.CustomerAddController;
import lk.ijse.sellingsystem.controller.CustomerOrderController;
import lk.ijse.sellingsystem.controller.VehicleController;
import lk.ijse.sellingsystem.core.dto.CustomerDTO;
import lk.ijse.sellingsystem.core.dto.CustomerOrderDTO;
import lk.ijse.sellingsystem.core.dto.VehicleDTO;
import lk.ijse.sellingsystem.dao.DAOFactory;
import lk.ijse.sellingsystem.idgenerator.IDGenerator;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Samishka
 */
@Report("lk.ijse.sellingsystem.report")
public class CustomerOrder extends javax.swing.JPanel {

    private CustomerAddController customeraddController;
    private DefaultTableModel dtmCustomer;

    /**
     * Creates new form CustomerOrder
     */
    public CustomerOrder() {
        initComponents();
        setDate();
        setOrderId();
        loadAllOrders();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDate = new org.jdesktop.swingx.JXTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        txtCustomerName = new org.jdesktop.swingx.JXTextField();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        txtAdvanceDate = new org.jdesktop.swingx.JXTextField();
        txtAdvance = new org.jdesktop.swingx.JXTextField();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        btnNew = new org.jdesktop.swingx.JXLabel();
        btnSave = new org.jdesktop.swingx.JXLabel();
        btnInvoice = new org.jdesktop.swingx.JXLabel();
        btnDelete = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderList = new org.jdesktop.swingx.JXTable();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtOrderId = new org.jdesktop.swingx.JXTextField();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        txtVehiclePrice = new org.jdesktop.swingx.JXTextField();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtVehicleId1 = new org.jdesktop.swingx.JXTextField();
        cmbCustomerId = new org.jdesktop.swingx.JXComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, 30));

        jXLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel9.setText("Order ID");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        txtCustomerName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomerName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 30));

        jXLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel5.setText("Customer  Name");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        jXLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel10.setText("Advance Date");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));

        txtAdvanceDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAdvanceDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAdvanceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvanceDateActionPerformed(evt);
            }
        });
        add(txtAdvanceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, 30));

        txtAdvance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAdvance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdvanceActionPerformed(evt);
            }
        });
        add(txtAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 110, 30));

        jXLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel11.setText("Advance ");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 80, 30));

        jXPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jXLabel2.setText("ORDER FORM");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -3, -1, 30));

        jXLabel1.setBackground(new java.awt.Color(235, 235, 235));
        jXPanel1.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 13, -1, -1));

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        jXPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setBackground(new java.awt.Color(153, 153, 153));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        jXPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        jXPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 40));

        btnInvoice.setBackground(new java.awt.Color(153, 153, 153));
        btnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/print1.png"))); // NOI18N
        btnInvoice.setText("PRINT");
        btnInvoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInvoice.setOpaque(true);
        btnInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseExited(evt);
            }
        });
        jXPanel2.add(btnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 90, 40));

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        jXPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 40));

        add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 390, 40));

        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Order Date", "Customer ID"
            }
        ));
        jScrollPane1.setViewportView(tblOrderList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 440, 490));

        jXLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel6.setText("Order List");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 100, 30));

        txtOrderId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtOrderId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });
        add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, 30));

        jXLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel13.setText("Date");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 30));

        jXLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel14.setText("Vehicle ID");
        jXLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 30));

        jXLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel16.setText("RMV payment");
        jXLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 30));

        txtVehiclePrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVehiclePrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVehiclePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiclePriceActionPerformed(evt);
            }
        });
        add(txtVehiclePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 110, 30));

        jXLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel7.setText("Customer   ID");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 30));

        txtVehicleId1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVehicleId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVehicleId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleId1ActionPerformed(evt);
            }
        });
        txtVehicleId1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicleId1KeyReleased(evt);
            }
        });
        add(txtVehicleId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, 30));

        cmbCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomerIdActionPerformed(evt);
            }
        });
        add(cmbCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtAdvanceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvanceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdvanceDateActionPerformed

    private void txtAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdvanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdvanceActionPerformed

    private void btnInvoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseEntered

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/print2.png"));
        btnInvoice.setIcon(icon);
    }//GEN-LAST:event_btnInvoiceMouseEntered

    private void btnInvoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseExited
        btnInvoice.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/print1.png"));
        btnInvoice.setIcon(icon);
    }//GEN-LAST:event_btnInvoiceMouseExited

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked

        // txtCustomerNIC.requestFocus();
        CustomerOrder order = new CustomerOrder();
        Home.MainPanel.removeAll();
        order.setSize(Home.MainPanel.getSize());
        Home.MainPanel.add(order);
        Home.MainPanel.revalidate();
        Home.MainPanel.repaint();

    }//GEN-LAST:event_btnNewMouseClicked

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add 4_1.png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked

        try {
            CustomerOrderDTO customerOrder;
            customerOrder=new CustomerOrderDTO(
                    txtOrderId.getText(),
                    txtDate.getText(),
                    cmbCustomerId.getSelectedItem().toString()
                    
            );
            boolean result = CustomerOrderController.addCustomer(customerOrder);
            
            if (result) {
                SupplierJOption2 mass = new SupplierJOption2();
                mass.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Customer hasn't been added due to some error");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllOrders();
        
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav3.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseExited

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtVehiclePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiclePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehiclePriceActionPerformed

    private void txtVehicleId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleId1ActionPerformed
       
          
       
    }//GEN-LAST:event_txtVehicleId1ActionPerformed

    private void cmbCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomerIdActionPerformed
        try {
            String itemId = (String) cmbCustomerId.getSelectedItem().toString();
            CustomerDTO customerDTO = new CustomerDTO();
            customerDTO.setId(itemId);
            CustomerDTO searchCustomer = CustomerAddController.searchCustomer(customerDTO);
            txtCustomerName.setText(searchCustomer.getName());
            txtAdvance.setText(searchCustomer.getAdvance().toString());
            txtCustomerName.setText(searchCustomer.getName());
            txtDate.setText(searchCustomer.getDate());
           txtVehicleId1.setText(searchCustomer.getVehicleId());
           txtAdvanceDate.setText(searchCustomer.getDate());
          
        } catch (Exception ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbCustomerIdActionPerformed

    private void txtVehicleId1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleId1KeyReleased
         
        try {
            String itemId = (String) cmbCustomerId.getSelectedItem().toString();
            VehicleDTO vehicle = new VehicleDTO();
            vehicle.setId(itemId);
            VehicleDTO searchCustomer = VehicleController.searchVehicle(vehicle);
            txtCustomerName.setText(searchCustomer.getPrice().toString());
        } catch (Exception ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtVehicleId1KeyReleased

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

        try {
            CustomerOrderDTO customerOrder=new CustomerOrderDTO(
                    txtOrderId.getText(),
                    cmbCustomerId.getSelectedItem().toString(),
                    txtDate.getText()
            );
            
            boolean result = CustomerOrderController.deleteCustomer(customerOrder);
            
            if (result) {
              

            } else {
                
            }
           
        } catch (Exception ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadAllOrders();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete5.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseClicked
        
        JasperUtil.init(CustomerOrder.class);

        JasperReportsContext ctx = JasperUtil.getReportContext();

        try {
            JasperReport compiledReport = JasperUtil.getCompiledReport("OrderDetails.jasper");
            
            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
            
            HashMap<String, Object> reportParams = new HashMap<>();
            
            TableModel model = tblOrderList.getModel();
            
            JasperPrint filledReport = fillManager.
                    fill(compiledReport, reportParams, new JRTableModelDataSource(model));
            
            IJSEJasperViewer frmJasperViewer = new IJSEJasperViewer(filledReport);
            frmJasperViewer.setTitle("Order List");
            frmJasperViewer.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            frmJasperViewer.setVisible(true);
            
            
        } catch (JRException ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnInvoiceMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel btnDelete;
    private org.jdesktop.swingx.JXLabel btnInvoice;
    private org.jdesktop.swingx.JXLabel btnNew;
    private org.jdesktop.swingx.JXLabel btnSave;
    private org.jdesktop.swingx.JXComboBox cmbCustomerId;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTable tblOrderList;
    private org.jdesktop.swingx.JXTextField txtAdvance;
    private org.jdesktop.swingx.JXTextField txtAdvanceDate;
    private org.jdesktop.swingx.JXTextField txtCustomerName;
    private org.jdesktop.swingx.JXTextField txtDate;
    private org.jdesktop.swingx.JXTextField txtOrderId;
    private org.jdesktop.swingx.JXTextField txtVehicleId1;
    private org.jdesktop.swingx.JXTextField txtVehiclePrice;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date d1 = new Date(); //request current data
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String fDate = df.format(d1);
        txtDate.setText(fDate);

    }

    private void setOrderId() {
        try {
            String orderId;
            orderId = IDGenerator.getNewID("customerOrders", "id", "CN");
            txtOrderId.setText(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllOrders() {
      
            
          
      
        try {
            
             
            try {
                ArrayList<CustomerOrderDTO> allCustomers = CustomerOrderController.getAllCustomers();
                
                DefaultTableModel dtm = (DefaultTableModel) tblOrderList.getModel();
                
                dtm.setRowCount(0);
                
                if (allCustomers != null) {
                    
                    for (CustomerOrderDTO orders : allCustomers) {
                        
                        Object[] rowData = {
                            orders.getId(),
                            orders.getOrderDate(),
                            
                            orders.getCustomerId(),};
                        
                        dtm.addRow(rowData);
                        
                    }
                    
                }
            } catch (Exception ex) {
                Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
            
            
            
            
            
            
            ArrayList<CustomerDTO>allCustomer=CustomerAddController.getAllCustomers();
            
            cmbCustomerId.removeAllItems();
            if(allCustomer==null) return;
            
            for (CustomerDTO allVehicle : allCustomer) {
                cmbCustomerId.addItem(allVehicle.getId());
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
           
             
        
           
      
           
            

        
        
     
    }

}
