/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;

/**
 *
 * @author Samishka
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn2
     */
    public LogIn() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLog = new org.jdesktop.swingx.JXLabel();
        lblloginbtn = new org.jdesktop.swingx.JXLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtuserName = new org.jdesktop.swingx.JXTextField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        back = new org.jdesktop.swingx.JXLabel();
        passPanel = new org.jdesktop.swingx.JXPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLog.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(txtLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 200, 20));

        lblloginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/image/login key.jpg"))); // NOI18N
        lblloginbtn.setToolTipText("Click Log in");
        lblloginbtn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblloginbtnAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblloginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblloginbtnMouseClicked(evt);
            }
        });
        getContentPane().add(lblloginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setNextFocusableComponent(lblloginbtn);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 260, 30));

        txtuserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtuserName.setPrompt("Enter user name");
        txtuserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtuserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 260, 30));

        jXLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jXLabel1.setText("Copyright 2017. All Rights Reserved.");
        getContentPane().add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 300, 70));

        jXLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 30));

        jXLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/icon-close.png"))); // NOI18N
        jXLabel3.setToolTipText("Close ");
        jXLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jXLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, 30));

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/image/Bagraund.png"))); // NOI18N
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        passPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(passPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 410, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblloginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginbtnMouseClicked

        String user = txtuserName.getText();
        if (user.matches("a")) {

            txtLog.setText("");
            txtPassword.requestFocus();
            txtLog.setForeground(Color.BLUE);
            //txtLog.setText("please Enter Password");

            String pass = txtPassword.getText();

            if (user.matches("a") && pass.matches("a")) {
                this.dispose();
                Home form = new Home();
                form.setVisible(true);
            } else {
                txtLog.setForeground(Color.BLUE);
                txtLog.setText("Enter Password");
            }

        } else {
            txtLog.setForeground(Color.red);
            txtLog.setText("The username is incorrect");
        }

////           
//      

    }//GEN-LAST:event_lblloginbtnMouseClicked

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
//        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
//        txtPassword.setText("*******");
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

        String user = txtuserName.getText();
        if (user.matches("a")) {

            txtLog.setText("");
            txtPassword.requestFocus();
            txtLog.setForeground(Color.BLUE);
           

            String pass = txtPassword.getText();

            if (user.matches("a") && pass.matches("a")) {
                this.dispose();
                Home form = new Home();
                form.setVisible(true);
            } else {
                txtLog.setForeground(Color.red);
                txtLog.setText("The Password is incorrect");
            }

        }


    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        txtPassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtuserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserNameActionPerformed

        String user = txtuserName.getText();
        if (user.matches("a")) {
            txtLog.setText("");
            txtPassword.requestFocus();

        } else {
            txtLog.setForeground(Color.red);
            txtLog.setText("The username is incorrect");
        }
    }//GEN-LAST:event_txtuserNameActionPerformed

    private void jXLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jXLabel2MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

    }//GEN-LAST:event_backMouseClicked

    private void jXLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jXLabel3MouseClicked

    private void lblloginbtnAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblloginbtnAncestorAdded
        String user = txtuserName.getText();
        String pass = txtPassword.getText();

        if (user.matches("a") && pass.matches("a")) {
            this.dispose();
            Home form = new Home();
            form.setVisible(true);
        } else {
            txtLog.setForeground(Color.BLUE);
            txtLog.setText("Enter User Name And Password");
        }


    }//GEN-LAST:event_lblloginbtnAncestorAdded

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked

        String user = txtuserName.getText();
        if (user.matches("a")) {
            txtLog.setText("");
            txtPassword.requestFocus();

        } else {
            txtLog.setText("The username is incorrect");
        }
    }//GEN-LAST:event_txtPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOutFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel back;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel lblloginbtn;
    private org.jdesktop.swingx.JXPanel passPanel;
    private org.jdesktop.swingx.JXLabel txtLog;
    private javax.swing.JPasswordField txtPassword;
    private org.jdesktop.swingx.JXTextField txtuserName;
    // End of variables declaration//GEN-END:variables

}
