/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Samishka
 */
public class SupplierOrder extends javax.swing.JPanel {

    /**
     * Creates new form SupplierOrder
     */
    public SupplierOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        txtCustomerAddress = new org.jdesktop.swingx.JXTextField();
        txtEmail = new org.jdesktop.swingx.JXTextField();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        txtPhoneno = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerView = new org.jdesktop.swingx.JXTable();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        btnNew = new org.jdesktop.swingx.JXLabel();
        btnDelete = new org.jdesktop.swingx.JXLabel();
        btnSave = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        txtPhoneno1 = new org.jdesktop.swingx.JXTextField();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel6.setText("Supplier ID");
        jXLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 100, 30));

        txtCustomerAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCustomerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerAddressActionPerformed(evt);
            }
        });
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 130, 30));

        txtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 130, 30));

        jXLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel9.setText("Batch ID");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, 30));

        jXLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel7.setText("Order ID");
        jXLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 30));

        txtPhoneno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPhoneno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPhoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhonenoActionPerformed(evt);
            }
        });
        add(txtPhoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, 30));

        tblCustomerView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Supplier ID", "Batch ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCustomerView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomerView);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 37, 520, 510));

        jXPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setBackground(new java.awt.Color(153, 153, 153));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        jXPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        jXPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 40));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        jXPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 40));

        add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 290, 40));

        jXPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jXLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jXLabel2.setText("SUPPLIER ORDER");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel2);

        jXLabel1.setBackground(new java.awt.Color(235, 235, 235));
        jXPanel1.add(jXLabel1);

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        txtPhoneno1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPhoneno1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPhoneno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneno1ActionPerformed(evt);
            }
        });
        add(txtPhoneno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 130, 30));

        jXLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel10.setText("Order  Date");
        jXLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAddressActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhonenoActionPerformed

    private void tblCustomerViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerViewMouseClicked
       

    }//GEN-LAST:event_tblCustomerViewMouseClicked

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
     
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add 4_1.png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete5.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav3.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseExited

    private void txtPhoneno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneno1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel btnDelete;
    private org.jdesktop.swingx.JXLabel btnNew;
    private org.jdesktop.swingx.JXLabel btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTable tblCustomerView;
    private org.jdesktop.swingx.JXTextField txtCustomerAddress;
    private org.jdesktop.swingx.JXTextField txtEmail;
    private org.jdesktop.swingx.JXTextField txtPhoneno;
    private org.jdesktop.swingx.JXTextField txtPhoneno1;
    // End of variables declaration//GEN-END:variables
}
