/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.sellingsystem.controller.BatchController;
import lk.ijse.sellingsystem.controller.CustomerAddController;
import lk.ijse.sellingsystem.controller.VehicleController;
import lk.ijse.sellingsystem.core.dto.BatchDTO;
import lk.ijse.sellingsystem.core.dto.CustomerDTO;
import lk.ijse.sellingsystem.core.dto.VehicleDTO;
import lk.ijse.sellingsystem.idgenerator.IDGenerator;
import static lk.ijse.sellingsystem.view.Home.MainPanel;

/**
 *
 * @author Samishka
 */
public class VehicleStore extends javax.swing.JPanel {

    /**
     * Creates new form VehicleStore
     */
    public VehicleStore() {
        initComponents();
        loadAllVehicles();
        loadCombobox();
        loadVehicleId();
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        txtVehiclePrice = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicleView = new org.jdesktop.swingx.JXTable();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        btnNew = new org.jdesktop.swingx.JXLabel();
        btnDelete = new org.jdesktop.swingx.JXLabel();
        btnSave = new org.jdesktop.swingx.JXLabel();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new org.jdesktop.swingx.JXTextArea();
        cmbVehicleBrand = new org.jdesktop.swingx.JXComboBox();
        cmbColor = new org.jdesktop.swingx.JXComboBox();
        cmbVehicleType = new org.jdesktop.swingx.JXComboBox();
        cmbManufacturer = new org.jdesktop.swingx.JXComboBox();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXLabel17 = new org.jdesktop.swingx.JXLabel();
        txtVehicleID = new org.jdesktop.swingx.JXTextField();
        jXLabel18 = new org.jdesktop.swingx.JXLabel();
        jXTextField1 = new org.jdesktop.swingx.JXTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel5.setText("Vehicle Color");
        jXLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 30));

        jXLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel8.setText("Vehicle Brand");
        jXLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        jXLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel9.setText("Description");
        jXLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 120, 30));

        txtVehiclePrice.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtVehiclePrice.setPrompt("000,000,000,00");
        txtVehiclePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiclePriceActionPerformed(evt);
            }
        });
        add(txtVehiclePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, 30));

        tblVehicleView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Vehicle Type", "Vehicle Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVehicleView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehicleViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehicleView);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 37, 520, 500));

        jXLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel11.setText("Manufacture year");
        jXLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 30));

        jXPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jXPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNew.setBackground(new java.awt.Color(153, 153, 153));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNew.setOpaque(true);
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        jXPanel2.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        jXPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 90, 40));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        jXPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 40));

        add(jXPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 290, 40));

        jXPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jXLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jXLabel2.setText("ADD VEHICLES");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXPanel1.add(jXLabel2);

        jXLabel1.setBackground(new java.awt.Color(235, 235, 235));
        jXPanel1.add(jXLabel1);

        add(jXPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 30));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane2.setViewportView(txtDesc);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 370, 110));
        add(cmbVehicleBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, 30));
        add(cmbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 30));
        add(cmbVehicleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 120, 30));
        add(cmbManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, 30));

        jXLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel13.setText("Vehicle price              $");
        jXLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 30));

        jXLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel14.setText("Vehicle Type");
        jXLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 30));

        jXLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel17.setText("Batch Id");
        jXLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 30));

        txtVehicleID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVehicleID.setForeground(new java.awt.Color(102, 102, 102));
        txtVehicleID.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        txtVehicleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIDActionPerformed(evt);
            }
        });
        add(txtVehicleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, 30));

        jXLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jXLabel18.setText("Vehicle ID");
        jXLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jXLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));
        add(jXTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehiclePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiclePriceActionPerformed
        // dfdf
    }//GEN-LAST:event_txtVehiclePriceActionPerformed

    private void tblVehicleViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehicleViewMouseClicked
        try {
            String vehicleId=(String) tblVehicleView.getValueAt(tblVehicleView.getSelectedRow(),0);
            VehicleDTO cuVehicleDTO=new VehicleDTO();
            cuVehicleDTO.setId(vehicleId);
            VehicleDTO searchVehicle=VehicleController.searchVehicle(cuVehicleDTO);
            txtVehicleID.setText(searchVehicle.getId());
            cmbVehicleBrand.setSelectedItem(searchVehicle.getBrand());
            cmbManufacturer.setSelectedItem(searchVehicle.getManuYear());
            cmbVehicleType.setSelectedItem(searchVehicle.getType());
            txtVehiclePrice.setText(searchVehicle.getPrice().toString());
            cmbColor.setSelectedItem(searchVehicle.getColor());
            txtDesc.setText(searchVehicle.getDescription());
            
           
        } catch (Exception ex) {
            Logger.getLogger(VehicleStore.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblVehicleViewMouseClicked

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked
        VehicleStore order = new VehicleStore();
        MainPanel.removeAll();
        order.setSize(MainPanel.getSize());
        MainPanel.add(order);
        MainPanel.revalidate();
        MainPanel.repaint();

    }//GEN-LAST:event_btnNewMouseClicked

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add 4_1.png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited
        btnNew.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/add (4).png"));
        btnNew.setIcon(icon);
    }//GEN-LAST:event_btnNewMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete5.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/delete4.png"));
        btnDelete.setIcon(icon);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked

        try {
            VehicleDTO vehicle;
            vehicle = new VehicleDTO(
                    txtVehicleID.getText(),
                    cmbVehicleType.getSelectedItem().toString(),
                    cmbVehicleBrand.getSelectedItem().toString(),
                    new BigDecimal(txtVehiclePrice.getText()),
                    cmbManufacturer.getSelectedItem().toString(),
                    cmbColor.getSelectedItem().toString(),
                    txtDesc.getText()
            );
            boolean result = VehicleController.addVehicle(vehicle);

            if (result) {
                SupplierJOption  mass = new SupplierJOption();
                mass.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Customer hasn't been added due to some error");
            }

        } catch (Exception ex) {
            Logger.getLogger(VehicleStore.class.getName()).log(Level.SEVERE, null, ex);
        }

        loadAllVehicles();


    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav3.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setForeground(Color.BLACK);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/lk/ijse/sellingsystem/view/icon/sav4.png"));
        btnSave.setIcon(icon);
    }//GEN-LAST:event_btnSaveMouseExited

    private void txtVehicleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXLabel btnDelete;
    private org.jdesktop.swingx.JXLabel btnNew;
    private org.jdesktop.swingx.JXLabel btnSave;
    private org.jdesktop.swingx.JXComboBox cmbColor;
    private org.jdesktop.swingx.JXComboBox cmbManufacturer;
    private org.jdesktop.swingx.JXComboBox cmbVehicleBrand;
    private org.jdesktop.swingx.JXComboBox cmbVehicleType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel17;
    private org.jdesktop.swingx.JXLabel jXLabel18;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXTextField jXTextField1;
    private org.jdesktop.swingx.JXTable tblVehicleView;
    private org.jdesktop.swingx.JXTextArea txtDesc;
    private org.jdesktop.swingx.JXTextField txtVehicleID;
    private org.jdesktop.swingx.JXTextField txtVehiclePrice;
    // End of variables declaration//GEN-END:variables

    private void loadCombobox() {
       
            //vehicle brands
            cmbVehicleBrand.addItem("Toyota");
            cmbVehicleBrand.addItem("Audi");
            cmbVehicleBrand.addItem("BMW");
            cmbVehicleBrand.addItem("Nissan");
            
            //vehicle Manufacturer year
            cmbManufacturer.addItem("2000");
            cmbManufacturer.addItem("2001");
            cmbManufacturer.addItem("2002");
            cmbManufacturer.addItem("2003");
            cmbManufacturer.addItem("2004");
            cmbManufacturer.addItem("2005");
            cmbManufacturer.addItem("2006");
            cmbManufacturer.addItem("2007");
            cmbManufacturer.addItem("2008");
            cmbManufacturer.addItem("2009");
            cmbManufacturer.addItem("2010");
            cmbManufacturer.addItem("2011");
            cmbManufacturer.addItem("2012");
            cmbManufacturer.addItem("2013");
            cmbManufacturer.addItem("2014");
            cmbManufacturer.addItem("2015");
            cmbManufacturer.addItem("2016");
            cmbManufacturer.addItem("2017");
            
            //type
            cmbVehicleType.addItem("economy car");
            cmbVehicleType.addItem("Family car");
            cmbVehicleType.addItem("Luxury vehicle");
            cmbVehicleType.addItem("Sports cars");
            cmbVehicleType.addItem("Off roaders");
            cmbVehicleType.addItem("Commercial vehicle");
            
            //color
            cmbColor.addItem("ALU	Aluminum");
            cmbColor.addItem("BEI	Beige");
            cmbColor.addItem("BLA	Black");
            cmbColor.addItem("BLU	Blue");
            cmbColor.addItem("BRO	Brown");
            cmbColor.addItem("BRZ	Bronze");
            cmbColor.addItem("CLA	Claret");
            cmbColor.addItem("COP	Copper");
            cmbColor.addItem("CRM	Cream");
            cmbColor.addItem("GOL	Gold");
            cmbColor.addItem("GRA	Gray");
            cmbColor.addItem("GRE	Green");
            cmbColor.addItem("MAR	Maroon");
            cmbColor.addItem("MTL	Metallic");
            cmbColor.addItem("NAV	Navy");
            cmbColor.addItem("ORA	Orange");
            cmbColor.addItem("PIN	Pink");
            cmbColor.addItem("PUR	Purple");
            cmbColor.addItem("RED	Red");
            cmbColor.addItem("ROS	Rose");
            cmbColor.addItem("RUS	Rust");
            cmbColor.addItem("SIL	Silver");
            cmbColor.addItem("TAN	Tan");
            cmbColor.addItem("TUR	Turquoise");
            cmbColor.addItem("WHI	White");
            cmbColor.addItem("YEL	Yellow");
            
       
       
    }
    

    private void loadVehicleId() {

        try {
            String orderId;
            orderId = IDGenerator.getNewVehicleID("vehicle", "id", "VI");
            txtVehicleID.setText(orderId);
        } catch (SQLException ex) {
            Logger.getLogger(VehicleStore.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadAllVehicles() {
        try {
            ArrayList<VehicleDTO> allCustomers = VehicleController.getAllVehicles();

            DefaultTableModel dtm = (DefaultTableModel) tblVehicleView.getModel();

            dtm.setRowCount(0);

            if (allCustomers != null) {

                for (VehicleDTO customer : allCustomers) {

                    Object[] rowData = {
                        customer.getId(),
                        customer.getBrand(),
                        customer.getPrice(),};

                    dtm.addRow(rowData);

                }

            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerAdd.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadnewCmb() throws Exception {
              
      
      
           
            
        
        
    }

  
}
