/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.sellingsystem.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import static lk.ijse.sellingsystem.view.Home.MainPanel;

/**
 *
 * @author ranjith-suranga
 */
public class WorningMsg extends javax.swing.JDialog {

    private Home msg;

    public WorningMsg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXLoginPane1 = new org.jdesktop.swingx.JXLoginPane();
        jXButton4 = new org.jdesktop.swingx.JXButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jXButton4.setText("CANCEL");
        jXButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXButton4MouseClicked(evt);
            }
        });
        jXButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jXButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 100, 30));

        jXButton2.setText("LOG OUT");
        jXButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jXButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 100, 30));

        jXLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jXLabel2.setText("are you sure?");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jXLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 210, 50));

        jXLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/sellingsystem/view/image/new home.jpg"))); // NOI18N
        getContentPane().add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 449, 183));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXButton2MouseClicked

        LogIn log = new LogIn();
        msg.dispose();
        log.setVisible(true);

    }//GEN-LAST:event_jXButton2MouseClicked

    private void jXButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXButton4MouseClicked
        dispose();
    }//GEN-LAST:event_jXButton4MouseClicked

    private void jXButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorningMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorningMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorningMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorningMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                WorningMsg dialog = new WorningMsg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton4;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLoginPane jXLoginPane1;
    // End of variables declaration//GEN-END:variables

    public void setting(Home msg) {
        this.msg = msg;
    }
}
